var gEventsVisible = {
	"0": true,
	"1": true,
	"2": true,
	"3": true,
	"4": true,
	"5": true,
	"6": true,
	"7": true,
	"8": false,
	"9": false,
};

var gEvents = [
	{
	"name": "Appearance Days of the Lord and His Incarnations",
	"bookid": "0",
	"events": [
		{
			"type": "T",
			"name": "Nrsimha Caturdasi: Appearance of Lord Nrsimhadeva",
			"tithi": 28,
			"masa": 0,
			"fastSubj": "Lord Nrsimhadeva",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Lord Balarama -- Appearance",
			"tithi": 29,
			"masa": 3,
			"fastSubj": "Lord Balarama",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Radhastami: Appearance of Srimati Radharani",
			"tithi": 22,
			"masa": 4,
			"fastSubj": "Srimati Radharani",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Vamana Dvadasi: Appearance of Lord Vamanadeva",
			"tithi": 26,
			"masa": 4,
			"fastSubj": "Vamanadeva",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Advaita Acarya -- Appearance",
			"tithi": 21,
			"masa": 9,
			"fastSubj": "Advaita Acarya",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Varaha Dvadasi: Appearance of Lord Varahadeva",
			"tithi": 26,
			"masa": 9,
			"fastSubj": "Varahadeva",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Nityananda Trayodasi: Appearance of Sri Nityananda Prabhu",
			"tithi": 27,
			"masa": 9,
			"fastSubj": "Sri Nityananda",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Sri Krsna Janmastami: Appearance of Lord Sri Krsna",
			"masa1": 4,
			"masa2": 4,
			"script": function(days,idx) {
				var a0 = 0;
				var a1 = 0;
				var a2 = 0;
				var d0 = days[idx-1];
				var d1 = days[idx];
				var d2 = days[idx+1];
				if (d0.ksayaTithi == 7) return 1;
				if (d0.astro.tithi == 7) a0 = 16;
				if (d1.astro.tithi == 7) a1 = 16;
				if (d2.astro.tithi == 7) a2 = 16;
				if (a1 == 0) return 0;
				if ((a0 < a1) && (a1 > a2)) return 1;
				if (d0.astro.naksatra == 3) a0 += 8;
				if (d1.astro.naksatra == 3) a1 += 8;
				if (d2.astro.naksatra == 3) a2 += 8;
				if ((a0 < a1) && (a1 > a2)) return 1;
				if ((a0 > a1) || (a2 > a1)) return 0;
				if (d0.midnightNaksatra == 3) a0 += 4;
				if (d1.midnightNaksatra == 3) a1 += 4;
				if (d2.midnightNaksatra == 3) a2 += 4;
				if ((a0 < a1) && (a1 > a2)) return 1;
				if ((a0 > a1) || (a2 > a1)) return 0;
				if (d0.date.weekday == 0) a0 += 2;
				if (d1.date.weekday == 0) a1 += 2;
				if (d2.date.weekday == 0) a2 += 2;
				if (d0.date.weekday == 2) a0 += 2;
				if (d1.date.weekday == 2) a1 += 2;
				if (d2.date.weekday == 2) a2 += 2;
				if (d2.astro.tithi == 7) a1 += 1;
				if ((a0 < a1) && (a1 > a2)) return 1;
				return 0;
			},
			"fastSubj": "Sri Krsna",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
			"events": [
				{
					"type": "R" ,
					"name": "Nandotsava",
					"fastSubj": "",
					"fast": 0,
					"start": -10000,
					"dayoff": 1,
				},
				{
					"type": "R" ,
					"name": "Srila Prabhupada -- Appearance",
					"fastSubj": "Srila Prabhupada",
					"fast": 0,
					"start": -10000,
					"dayoff": 1,
				},
			]		},
		{
			"type": "T",
			"name": "Gaura Purnima: Appearance of Sri Caitanya Mahaprabhu",
			"tithi": 29,
			"masa": 10,
			"fastSubj": "Sri Krsna Caitanya Mahaprabhu",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Rama Navami: Appearance of Lord Sri Ramacandra",
			"masa1": 11,
			"masa2": 11,
			"script": function(days,idx) {
				var d0 = days[idx-1];
				var d1 = days[idx];
				var d2 = days[idx+1];
				var d3 = days[idx+2];
				//console.log('Rama navami func idx:', idx, days[idx-1].ksayaTithi, d0.astro.tithi)
				if (d0.ksayaTithi == 23) return 1;
				if (d0.astro.tithi == 23) return 0;
				/*console.log('d1 tithi=', d1.astro.tithi, d1.date);
				console.log('d2 tithi=', d2.astro.tithi, d2.date);
				console.log('d3 fasttype=', d3);*/
				if ((d2.astro.tithi == 23) && (d3.fastType > 0)) return 1;
				if ((d1.astro.tithi == 23) && (d2.fastType == 0)) return 1;
				return 0;
			},
			"fastSubj": "Sri Ramacandra",
			"fast": 7,
			"start": -10000,
			"dayoff": 0,
		},
	]
},
{
	"name": "Events in the Pastimes of the Lord and His Associates",
	"bookid": "1",
	"events": [
		{
			"type": "T",
			"name": "Aksaya Trtiya. Candana Yatra starts. (Continues for 21 days)",
			"tithi": 17,
			"masa": 0,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srimati Sita Devi (consort of Lord Sri Rama) -- Appearance",
			"tithi": 23,
			"masa": 0,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Rukmini Dvadasi",
			"tithi": 26,
			"masa": 0,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Krsna Phula Dola, Salila Vihara",
			"tithi": 29,
			"masa": 0,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Sri Radha-Ramana Devaji -- Appearance",
			"tithi": 29,
			"masa": 0,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Ganga Puja",
			"tithi": 24,
			"masa": 1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Panihati Cida Dahi Utsava",
			"tithi": 27,
			"masa": 1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Snana Yatra",
			"tithi": 29,
			"masa": 1,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Guru (Vyasa) Purnima",
			"tithi": 29,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Radha Govinda Jhulana Yatra begins",
			"tithi": 25,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Jhulana Yatra ends",
			"tithi": 29,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Ananta Caturdasi Vrata",
			"tithi": 28,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Visvarupa Mahotsava",
			"tithi": 29,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Ramacandra Vijayotsava",
			"tithi": 24,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Krsna Saradiya Rasayatra",
			"tithi": 29,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Appearance of Radha Kunda, snana dana",
			"tithi": 7,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Bahulastami",
			"tithi": 7,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Dipa dana, Dipavali, (Kali Puja)",
			"tithi": 14,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Bali Daityaraja Puja",
			"tithi": 15,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Gopastami, Gosthastami",
			"tithi": 22,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Krsna Rasayatra",
			"tithi": 29,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Tulasi-Saligrama Vivaha (marriage)",
			"tithi": 29,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Katyayani vrata begins",
			"tithi": 0,
			"masa": 7,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Odana sasthi",
			"tithi": 20,
			"masa": 7,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Advent of Srimad Bhagavad-gita",
			"tithi": 25,
			"masa": 7,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Katyayani vrata ends",
			"tithi": 29,
			"masa": 7,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Krsna Pusya Abhiseka",
			"tithi": 29,
			"masa": 8,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Vasanta Pancami",
			"tithi": 19,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Bhismastami",
			"tithi": 22,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Krsna Madhura Utsava",
			"tithi": 29,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Siva Ratri",
			"tithi": 13,
			"masa": 10,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Damanakaropana Dvadasi",
			"tithi": 26,
			"masa": 11,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Balarama Rasayatra",
			"tithi": 29,
			"masa": 11,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Krsna Vasanta Rasa",
			"tithi": 29,
			"masa": 11,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Go Puja. Go Krda. Govardhana Puja.",
			"masa1": 6,
			"masa2": 6,
			"script": function(days,idx) {
				var a0 = 0;
				var a1 = 0;
				var a2 = 0;
				var d0 = days[idx-1];
				var d1 = days[idx];
				var d2 = days[idx+1];

				if (d1.astro.masa != 6) return 0;
				if (d0.ksayaTithi == 15) return 1;
				if (d0.astro.tithi == 15) { a0 = 16; }
				if (d1.astro.tithi == 15) { a1 = 16; }
				if (d2.astro.tithi == 15) { a2 = 16; }
				if (a1 == 0) return 0;
				if ((a0 < a1) && (a1 > a2)) return 1;
				if (d0.moonRiseSec < d0.sunRiseSec) a0 += 8;
				if (d1.moonRiseSec < d1.sunRiseSec) a1 += 8;
				if (d2.moonRiseSec < d2.sunRiseSec) a2 += 8;
				if ((a0 > a1) || (a2 > a1)) { return 0 }
				return 1;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Ratha Yatra",
			"tithi": 16,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Gundica Marjana",
			"tithi": 16,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "T",
			"name": "Return Ratha (8 days after Ratha Yatra)",
			"tithi": 16,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 8,
		},
		{
			"type": "T",
			"name": "Hera Pancami (4 days after Ratha Yatra)",
			"tithi": 16,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 4,
		},
		{
			"type": "T",
			"name": "Festival of Jagannatha Misra",
			"tithi": 29,
			"masa": 10,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 1,
		},
		{
			"type": "E",
			"name": "First day of Bhisma Pancaka",
			"masa": 6,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of Bhisma Pancaka",
			"tithi": 29,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
	]
},
{
	"name": "Appearance and Disappearance Days of Recent Acaryas",
	"bookid": "2",
	"events": [
		{
			"type": "T",
			"name": "Srila Bhaktivinoda Thakura -- Disappearance",
			"tithi": 14,
			"masa": 2,
 			"fastSubj": "Bhaktivinoda Thakura",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Vamsidasa Babaji -- Disappearance",
			"tithi": 18,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Bhaktivinoda Thakura -- Appearance",
			"tithi": 27,
			"masa": 4,
 			"fastSubj": "Bhaktivinoda Thakura",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Madhvacarya -- Appearance",
			"tithi": 24,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Prabhupada -- Disappearance",
			"tithi": 18,
			"masa": 6,
 			"fastSubj": "Srila Prabhupada",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Gaura Kisora Dasa Babaji -- Disappearance",
			"tithi": 25,
			"masa": 6,
 			"fastSubj": "Gaura Kisora Dasa Babaji",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Bhaktisiddhanta Sarasvati Thakura -- Disappearance",
			"tithi": 3,
			"masa": 8,
 			"fastSubj": "Bhaktisiddhanta Sarasvati",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Bhaktisiddhanta Sarasvati Thakura -- Appearance",
			"tithi": 4,
			"masa": 10,
 			"fastSubj": "Bhaktisiddhanta Sarasvati",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Jagannatha Dasa Babaji -- Disappearance",
			"tithi": 15,
			"masa": 10,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
	]
},
{
	"name": "Appearance and Disappearance Days of Mahaprabhu's Associates and Other Acaryas",
	"bookid": "3",
	"events": [
		{
			"type": "T",
			"name": "Sri Abhirama Thakura -- Disappearance",
			"tithi": 6,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Vrndavana Dasa Thakura -- Disappearance",
			"tithi": 9,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Gadadhara Pandita -- Appearance",
			"tithi": 14,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Madhu Pandita -- Disappearance",
			"tithi": 23,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srimati Jahnava Devi -- Appearance",
			"tithi": 23,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Paramesvari Dasa Thakura -- Disappearance",
			"tithi": 29,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Madhavendra Puri -- Appearance",
			"tithi": 29,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Srinivasa Acarya -- Appearance",
			"tithi": 29,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Ramananda Raya -- Disappearance",
			"tithi": 4,
			"masa": 1,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Vrndavana Dasa Thakura -- Appearance",
			"tithi": 11,
			"masa": 1,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Baladeva Vidyabhusana -- Disappearance",
			"tithi": 24,
			"masa": 1,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srimati Gangamata Gosvamini -- Appearance",
			"tithi": 24,
			"masa": 1,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Mukunda Datta -- Disappearance",
			"tithi": 29,
			"masa": 1,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Sridhara Pandita -- Disappearance",
			"tithi": 29,
			"masa": 1,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Syamananda Prabhu -- Disappearance",
			"tithi": 0,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Vakresvara Pandita -- Appearance",
			"tithi": 4,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Srivasa Pandita -- Disappearance",
			"tithi": 9,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Gadadhara Pandita -- Disappearance",
			"tithi": 14,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Svarupa Damodara Gosvami -- Disappearance",
			"tithi": 16,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Sivananda Sena -- Disappearance",
			"tithi": 16,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Vakresvara Pandita -- Disappearance",
			"tithi": 20,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Sanatana Gosvami -- Disappearance",
			"tithi": 29,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Gopala Bhatta Gosvami -- Disappearance",
			"tithi": 4,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Lokanatha Gosvami -- Disappearance",
			"tithi": 7,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Raghunandana Thakura -- Disappearance",
			"tithi": 18,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Rupa Gosvami -- Disappearance",
			"tithi": 26,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Gauridasa Pandita -- Disappearance",
			"tithi": 26,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srimati Sita Thakurani (Sri Advaita's consort) -- Appearance",
			"tithi": 19,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Jiva Gosvami -- Appearance",
			"tithi": 26,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Haridasa Thakura -- Disappearance",
			"tithi": 28,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Raghunatha Dasa Gosvami -- Disappearance",
			"tithi": 26,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Raghunatha Bhatta Gosvami -- Disappearance",
			"tithi": 26,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Krsnadasa Kaviraja Gosvami -- Disappearance",
			"tithi": 26,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Murari Gupta -- Disappearance",
			"tithi": 29,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Narottama Dasa Thakura -- Disappearance",
			"tithi": 4,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Virabhadra -- Appearance",
			"tithi": 8,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Rasikananda -- Appearance",
			"tithi": 15,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Vasudeva Ghosh -- Disappearance",
			"tithi": 16,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Gadadhara Dasa Gosvami -- Disappearance",
			"tithi": 22,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Dhananjaya Pandita -- Disappearance",
			"tithi": 22,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Srinivasa Acarya -- Disappearance",
			"tithi": 22,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Bhugarbha Gosvami -- Disappearance",
			"tithi": 28,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Kasisvara Pandita -- Disappearance",
			"tithi": 28,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Nimbarkacarya -- Appearance",
			"tithi": 29,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Narahari Sarakara Thakura -- Disappearance",
			"tithi": 10,
			"masa": 7,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Kaliya Krsnadasa -- Disappearance",
			"tithi": 11,
			"masa": 7,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Saranga Thakura -- Disappearance",
			"tithi": 12,
			"masa": 7,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Devananda Pandita -- Disappearance",
			"tithi": 10,
			"masa": 8,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Mahesa Pandita -- Disappearance",
			"tithi": 12,
			"masa": 8,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Uddharana Datta Thakura -- Disappearance",
			"tithi": 12,
			"masa": 8,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Locana Dasa Thakura -- Appearance",
			"tithi": 15,
			"masa": 8,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Jiva Gosvami -- Disappearance",
			"tithi": 17,
			"masa": 8,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Jagadisa Pandita -- Disappearance",
			"tithi": 17,
			"masa": 8,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Jagadisa Pandita -- Appearance",
			"tithi": 26,
			"masa": 8,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Ramacandra Kaviraja -- Disappearance",
			"tithi": 4,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Gopala Bhatta Gosvami -- Appearance",
			"tithi": 4,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Jayadeva Gosvami -- Disappearance",
			"tithi": 5,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Locana Dasa Thakura -- Disappearance",
			"tithi": 6,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srimati Visnupriya Devi -- Appearance",
			"tithi": 19,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Visvanatha Cakravarti Thakura -- Disappearance",
			"tithi": 19,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Pundarika Vidyanidhi -- Appearance",
			"tithi": 19,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Raghunandana Thakura -- Appearance",
			"tithi": 19,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Raghunatha Dasa Gosvami -- Appearance",
			"tithi": 19,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Madhvacarya -- Disappearance",
			"tithi": 23,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Ramanujacarya -- Disappearance",
			"tithi": 24,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Narottama Dasa Thakura -- Appearance",
			"tithi": 29,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Purusottama Das Thakura -- Disappearance",
			"tithi": 4,
			"masa": 10,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Isvara Puri -- Disappearance",
			"tithi": 11,
			"masa": 10,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Rasikananda -- Disappearance",
			"tithi": 15,
			"masa": 10,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Purusottama Dasa Thakura -- Appearance",
			"tithi": 18,
			"masa": 10,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Madhavendra Puri -- Disappearance",
			"tithi": 26,
			"masa": 10,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Srivasa Pandita -- Appearance",
			"tithi": 7,
			"masa": 11,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Govinda Ghosh -- Disappearance",
			"tithi": 11,
			"masa": 11,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Ramanujacarya -- Appearance",
			"tithi": 19,
			"masa": 11,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Vamsivadana Thakura -- Appearance",
			"tithi": 29,
			"masa": 11,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sri Syamananda Prabhu -- Appearance",
			"tithi": 29,
			"masa": 11,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
	]
},
{
	"name": "ISKCON's Historical Events",
	"bookid": "4",
	"events": [
		{
			"type": "T",
			"name": "Sri Jayananda Prabhu -- Disappearance",
			"tithi": 27,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "The incorporation of ISKCON in New York",
			"tithi": 8,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Prabhupada's departure for the USA",
			"tithi": 0,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Acceptance of sannyasa by Srila Prabhupada",
			"tithi": 29,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Srila Prabhupada's arrival in the USA",
			"tithi": 6,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
	]
},
{
	"name": "Bengal-specific Holidays",
	"bookid": "5",
	"events": [
		{
			"type": "T",
			"name": "Jahnu Saptami",
			"tithi": 21,
			"masa": 0,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Durga Puja",
			"tithi": 21,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Laksmi Puja",
			"tithi": 29,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Jagaddhatri Puja",
			"tithi": 23,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Sarasvati Puja",
			"tithi": 19,
			"masa": 9,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "S",
			"name": "Ganga Sagara Mela",
			"sankranti": 9,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "S",
			"name": "Tulasi Jala Dan begins",
			"sankranti": 0,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "S",
			"name": "Tulasi Jala Dan ends",
			"sankranti": 1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
	]
},
{
	"name": "My Personal Events",
	"bookid": "6",
	"events": [
	]
},
{
	"name": "Caturmasya (Pratipat System)",
	"bookid": "7",
	"events": [
		{
			"type": "T",
			"name": "First month of Caturmasya begins (Pratipat System)",
			"tithi": 0,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "(green leafy vegetable fast for one month)",
			"tithi": 0,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of the first Caturmasya month",
			"tithi": 0,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "T",
			"name": "Second month of Caturmasya begins (Pratipat System)",
			"tithi": 0,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "(yogurt fast for one month)",
			"tithi": 0,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of the second Caturmasya month",
			"tithi": 0,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "T",
			"name": "Third month of Caturmasya begins (Pratipat System)",
			"tithi": 0,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "(milk fast for one month)",
			"tithi": 0,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of the third Caturmasya month",
			"tithi": 0,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "T",
			"name": "Fourth month of Caturmasya begins (Pratipat System)",
			"tithi": 0,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "(urad dal fast for one month)",
			"tithi": 0,
			"masa": 6,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of the fourth Caturmasya month",
			"tithi": 0,
			"masa": 7,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "X",
			"name": "First month of Caturmasya continues",
			"masa1": 3,
			"masa2": 3,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 3) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Second month of Caturmasya continues",
			"masa1": 4,
			"masa2": 4,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 4) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Third month of Caturmasya continues",
			"masa1": 5,
			"masa2": 5,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 5) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Fourth month of Caturmasya continues",
			"masa1": 6,
			"masa2": 6,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 6) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
	]
},
{
	"name": "Caturmasya (Purnima System)",
	"bookid": "8",
	"events": [
		{
			"type": "T",
			"name": "First month of Caturmasya begins (Purnima System)",
			"tithi": 29,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "(green leafy vegetable fast for one month)",
			"tithi": 29,
			"masa": 2,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of the first Caturmasya month",
			"tithi": 29,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "T",
			"name": "Second month of Caturmasya begins (Purnima System)",
			"tithi": 29,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "(yogurt fast for one month)",
			"tithi": 29,
			"masa": 3,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of the second Caturmasya month",
			"tithi": 29,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "T",
			"name": "Third month of Caturmasya begins (Purnima System)",
			"tithi": 29,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "(milk fast for one month)",
			"tithi": 29,
			"masa": 4,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of the third Caturmasya month",
			"tithi": 29,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "T",
			"name": "Fourth month of Caturmasya begins (Purnima System)",
			"tithi": 29,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "(urad dal fast for one month)",
			"tithi": 29,
			"masa": 5,
 			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "T",
			"name": "Last day of the fourth Caturmasya month",
			"tithi": 29,
			"masa": 6,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "X",
			"name": "First month of Caturmasya continues",
			"masa1": 3,
			"masa2": 3,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 3) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Second month of Caturmasya continues",
			"masa1": 4,
			"masa2": 4,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 4) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Third month of Caturmasya continues",
			"masa1": 5,
			"masa2": 5,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 5) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Fourth month of Caturmasya continues",
			"masa1": 6,
			"masa2": 6,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 6) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
	]
},
{
	"name": "Caturmasya (Ekadasi System)",
	"bookid": "9",
	"events": [
		{
			"type": "E",
			"name": "First month of Caturmasya begins (Ekadasi System)",
			"masa": 2,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "E",
			"name": "(green leafy vegetable fast for one month)",
			"masa": 2,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "E",
			"name": "Last day of the first Caturmasya month",
			"masa": 3,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "E",
			"name": "Second month of Caturmasya begins (Ekadasi System)",
			"masa": 3,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "E",
			"name": "(yogurt fast for one month)",
			"masa": 3,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "E",
			"name": "Last day of the second Caturmasya month",
			"masa": 4,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "E",
			"name": "Third month of Caturmasya begins (Ekadasi System)",
			"masa": 4,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "E",
			"name": "(milk fast for one month)",
			"masa": 4,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "E",
			"name": "Last day of the third Caturmasya month",
			"masa": 5,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "E",
			"name": "Fourth month of Caturmasya begins (Ekadasi System)",
			"masa": 5,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "E",
			"name": "(urad dal fast for one month)",
			"masa": 5,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "E",
			"name": "Last day of the fourth Caturmasya month",
			"masa": 6,
			"paksa":  1,
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": -1,
		},
		{
			"type": "X",
			"name": "First month of Caturmasya continues",
			"masa1": 3,
			"masa2": 3,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 3) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Second month of Caturmasya continues",
			"masa1": 4,
			"masa2": 4,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 4) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Third month of Caturmasya continues",
			"masa1": 5,
			"masa2": 5,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 5) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
		{
			"type": "X",
			"name": "Fourth month of Caturmasya continues",
			"masa1": 6,
			"masa2": 6,
			"script": function(days,idx) {
				var d0 = days[idx - 1];
				var d1 = days[idx];
				if (d0.astro.masa == 12 && d1.astro.masa == 6) {
					return 1;
				}
				return 0;
			},
			"fastSubj": "",
			"fast": 0,
			"start": -10000,
			"dayoff": 0,
		},
	]},
];
